### ISSUE TITLE
A connection failure may not abort the stream

### ISSUE THREAD

**Issue by pfraze** [ssbc/muxrpc#13]
...or, at least, it didnt stop `pull-inactivity` from polling.

The error received was:

```
{ [Error: connect EHOSTUNREACH]
  code: 'EHOSTUNREACH',
  errno: 'EHOSTUNREACH',
  syscall: 'connect',
  target: 
   { domain: null,
     _events: 
      { message: [Object],
        close: [Object],
        error: [Object],
        open: [Object] },
     _maxListeners: 10,
     _socket: null,
     _ultron: null,
     bytesReceived: 0,
     readyState: 0,
     supports: { binary: true },
     _isServer: false,
     url: 'grimwire.com:2000',
     protocolVersion: 13 } } Error: connect EHOSTUNREACH
    at errnoException (net.js:904:11)
    at connect (net.js:766:19)
    at net.js:845:9
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:121:9)
```

**Comment by dominictarr** [comment]
this hasn't been a problem in ages. guess it's fixed. closing.
